name: image_carousel
description: A very simple image carousel with transform effects and page indicators
version: 0.2.6
homepage: https://omegadesign.no
repository: https://github.com/Omega-Design-AS/package-image-carousel
publish_to: 'https://flutter-packages.appframe.com:4242'

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  image_viewer :
    git:
      url: 'https://github.com/Omega-Design-AS/package-image-viewer.git'
  animations: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
